### ISSUE TITLE
Turn Depends into Imports

### ISSUE THREAD

**Issue by muschellij2** [adigherman/neurocStats#1]
From http://r-pkgs.had.co.nz/namespace.html
> Unless there is a good reason otherwise, you should always list packages in Imports not Depends. That’s because a good package is self-contained, and minimises changes to the global environment (including the search path). The only exception is if your package is designed to be used in conjunction with another package. For example, the analogue package builds on top of vegan. It’s not useful without vegan, so it has vegan in Depends instead of Imports. Similarly, ggplot2 should really Depend on scales, rather than Importing it.

**Comment by adigherman** [comment]
Makes sense. Thanks for the heads-up! I've fixed it and tagged the commit with `submit_package_release` for Neuroc.
