### ISSUE TITLE
Package details not appropriate

### ISSUE THREAD

**Issue by muschellij2** [adigherman/neurocStats#2]
```r
x = neurocStats::get_package_details("dcm2niir")
```
this gives the description, whereas the API indicates that https://neuroconductor.org/api-docs/package-details is really what it should point to or really https://neuroconductor.org/api-docs/package

**Comment by adigherman** [comment]
Yep. I'm changing that function name/description and create a new one that will return the correct info.

**Comment by adigherman** [comment]
Fixed
